packages:
  - .
allowBuilds:
  '"': true
  ',': true
  '-': true
  /: true
  '@': true
  '[': true
  ']': true
  c: true
  e: true
  f: true
  i: true
  l: true
  o: true
  r: true
  s: true
  u: true
  w: true
